"""Postgres 資料存取層：整個 pipeline（ingest / embed / classify / trend / recommend /
report / interact）共用同一份 Postgres 資料庫（Neon），這個模組集中管理 schema 定義與所有
讀寫函式，其他模組不直接寫 SQL，一律透過這裡提供的函式存取資料庫。
"""

import os
from datetime import datetime, timezone
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row

# 本機開發時從專案根目錄的 .env 讀 DATABASE_URL（neon link 產生，已 gitignore）；
# 部署到 Render 時則由 Render Dashboard 設定同名環境變數，load_dotenv 不會覆蓋它。
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# 整個系統用到的資料表定義。用 CREATE TABLE IF NOT EXISTS 是為了讓 init_db()
# 可以每次啟動都安全地重複執行，不需要額外的 migration 機制。
# 時間欄位沿用 ISO 8601 字串（TEXT），跟 SQLite 時期的資料格式一致，字串排序即時間排序。
SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    source       TEXT NOT NULL,
    source_id    TEXT NOT NULL,
    title        TEXT NOT NULL,
    description  TEXT NOT NULL,
    url          TEXT NOT NULL,
    author       TEXT,
    category     TEXT,
    metric       BIGINT,
    published_at TEXT,
    fetched_at   TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS metric_snapshots (
    source      TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    metric      BIGINT NOT NULL,
    snapshot_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS embeddings (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    model      TEXT NOT NULL,
    vector     BYTEA NOT NULL,
    dim        INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS item_tags (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    tag        TEXT NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id, tag)
);

CREATE TABLE IF NOT EXISTS trend_scores (
    source      TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    score       DOUBLE PRECISION NOT NULL,
    basis       TEXT NOT NULL,
    computed_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS interactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    action     TEXT NOT NULL CHECK (action IN ('like', 'skip')),
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS narrations (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    narration  TEXT NOT NULL,
    model      TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE INDEX IF NOT EXISTS metric_snapshots_source_idx ON metric_snapshots (source, snapshot_at);
"""


def get_connection() -> psycopg.Connection:
    """建立一個新的資料庫連線，搭配 with 使用：離開區塊時自動 commit 並關閉連線。

    刻意每次都開新連線、用完就關，而不是維持常駐連線池：Neon 免費方案在沒有連線
    5 分鐘後才會休眠，常駐連線會讓資料庫一直醒著，把每月的免費運算時數燒光。
    DATABASE_URL 用的是 Neon 的 pooled endpoint（PgBouncer transaction mode），
    所以關掉 psycopg 的自動 prepared statement（prepare_threshold=None），避免跨連線衝突。
    """
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL 沒有設定：本機請在專案根目錄執行 neon link 產生 .env，部署環境請在 Render 設定環境變數。")
    return psycopg.connect(url, prepare_threshold=None, connect_timeout=15)


def init_db() -> None:
    """依 SCHEMA 建立所有資料表（已存在的表不會被動到），API 啟動、每支腳本執行前都會呼叫一次。"""
    with get_connection() as conn:
        for statement in SCHEMA.split(";"):
            if statement.strip():
                conn.execute(statement)


def upsert_items(items: list[dict]) -> int:
    """寫入項目，遇到已存在的（依 source+source_id 判斷）就略過，不覆蓋。

    回傳這次呼叫實際新增的筆數，讓呼叫端可以知道「這次抓到幾筆全新的項目」，
    而不是「這次總共處理了幾筆」。
    """
    with get_connection() as conn:
        cur = conn.cursor()
        cur.executemany(
            """
            INSERT INTO items
                (source, source_id, title, description, url, author, category, metric, published_at, fetched_at)
            VALUES
                (%(source)s, %(source_id)s, %(title)s, %(description)s, %(url)s, %(author)s, %(category)s,
                 %(metric)s, %(published_at)s, %(fetched_at)s)
            ON CONFLICT (source, source_id) DO NOTHING
            """,
            items,
        )
        return cur.rowcount


def record_snapshots(items: list[dict]) -> None:
    """不管項目本身是不是新的，每次抓取都幫每個項目多寫一筆指標快照（metric snapshot）。

    這是刻意設計成「每次都寫」而不是「只在項目是新的時候才寫」：
    之後計算「成長率」型的熱度分數（trend score）需要同一個項目在不同時間點的指標序列，
    只有持續累積快照才能還原出這條時間序列。
    """
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO metric_snapshots (source, source_id, metric, snapshot_at)
            VALUES (%(source)s, %(source_id)s, %(metric)s, %(fetched_at)s)
            """,
            items,
        )


def get_items_missing_embeddings() -> list[dict]:
    """找出 items 裡還沒有對應 embedding 紀錄的項目，供 embed.py 增量處理。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            """
            SELECT items.source, items.source_id, items.title, items.description
            FROM items
            LEFT JOIN embeddings
                ON items.source = embeddings.source AND items.source_id = embeddings.source_id
            WHERE embeddings.source_id IS NULL
            """
        ).fetchall()
        return [dict(row) for row in rows]


def upsert_embeddings(rows: list[dict]) -> None:
    """寫入 embedding 向量。每筆 row 需包含：source, source_id, model, vector（bytes）, dim, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO embeddings (source, source_id, model, vector, dim, created_at)
            VALUES (%(source)s, %(source_id)s, %(model)s, %(vector)s, %(dim)s, %(created_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                model = EXCLUDED.model, vector = EXCLUDED.vector, dim = EXCLUDED.dim, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def get_all_embeddings() -> list[dict]:
    """讀出所有項目的 embedding 向量，供 classify.py / api.py 的語意搜尋做線性掃描比對。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute("SELECT source, source_id, vector, dim FROM embeddings").fetchall()
        return [dict(row) for row in rows]


def upsert_tags(rows: list[dict]) -> None:
    """寫入標籤分類結果。每筆 row 需包含：source, source_id, tag, score, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO item_tags (source, source_id, tag, score, created_at)
            VALUES (%(source)s, %(source_id)s, %(tag)s, %(score)s, %(created_at)s)
            ON CONFLICT (source, source_id, tag) DO UPDATE SET
                score = EXCLUDED.score, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def upsert_trend_scores(rows: list[dict]) -> None:
    """寫入熱度分數。每筆 row 需包含：source, source_id, score, basis, computed_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO trend_scores (source, source_id, score, basis, computed_at)
            VALUES (%(source)s, %(source_id)s, %(score)s, %(basis)s, %(computed_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                score = EXCLUDED.score, basis = EXCLUDED.basis, computed_at = EXCLUDED.computed_at
            """,
            rows,
        )


def get_all_trend_scores() -> dict:
    """回傳 (source, source_id) -> 熱度分數 的對照表，方便其他模組整批查詢。"""
    with get_connection() as conn:
        rows = conn.execute("SELECT source, source_id, score FROM trend_scores").fetchall()
        return {(source, source_id): score for source, source_id, score in rows}


def record_interaction(source: str, source_id: str, action: str) -> None:
    """記錄一次使用者互動（按讚或略過），時間戳記統一用 UTC，避免跨時區比較時出錯。"""
    with get_connection() as conn:
        conn.execute(
            "INSERT INTO interactions (source, source_id, action, created_at) VALUES (%s, %s, %s, %s)",
            (source, source_id, action, datetime.now(timezone.utc).isoformat()),
        )


def get_latest_interactions() -> dict:
    """回傳 (source, source_id) -> 最新一次的動作（'like'/'skip'）。

    同一個項目可能被使用者按讚後又改成略過（或反過來），這裡只取每組
    (source, source_id) 裡 id 最大（也就是最新）的那一筆，讓「改變心意」可以覆蓋掉舊的判斷。
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT source, source_id, action FROM interactions
            WHERE id IN (SELECT MAX(id) FROM interactions GROUP BY source, source_id)
            """
        ).fetchall()
        return {(source, source_id): action for source, source_id, action in rows}


def get_item(source: str, source_id: str) -> dict | None:
    """依 (source, source_id) 查單一項目的完整欄位；查無資料回傳 None。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        row = conn.execute(
            "SELECT * FROM items WHERE source = %s AND source_id = %s", (source, source_id)
        ).fetchone()
        return dict(row) if row else None


def get_items(source: str | None = None, tag: str | None = None, limit: int = 50, offset: int = 0) -> list[dict]:
    """分頁列出項目，可選擇依來源（source）與標籤（tag）篩選。

    SQL 是用字串組合動態拼出來的：只有在有指定 tag 時才 JOIN item_tags 表、
    只有在有指定 source/tag 時才加對應的 WHERE 條件，避免不需要篩選時多做不必要的 JOIN。
    """
    query = "SELECT DISTINCT items.* FROM items"
    params: list = []
    where = []
    if tag:
        query += " JOIN item_tags ON items.source = item_tags.source AND items.source_id = item_tags.source_id"
        where.append("item_tags.tag = %s")
        params.append(tag)
    if source:
        where.append("items.source = %s")
        params.append(source)
    if where:
        query += " WHERE " + " AND ".join(where)
    query += " ORDER BY items.published_at DESC LIMIT %s OFFSET %s"
    params += [limit, offset]

    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(query, params).fetchall()
        return [dict(row) for row in rows]


def get_item_tags(source: str, source_id: str) -> list[dict]:
    """取得單一項目的所有標籤，依分數（score）由高到低排序。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT tag, score FROM item_tags WHERE source = %s AND source_id = %s ORDER BY score DESC",
            (source, source_id),
        ).fetchall()
        return [dict(row) for row in rows]


def get_tags_with_counts() -> list[dict]:
    """列出所有標籤與各自被使用的次數，依次數由多到少排序，供前端做標籤雲/篩選清單。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT tag, COUNT(*) as count FROM item_tags GROUP BY tag ORDER BY count DESC"
        ).fetchall()
        return [dict(row) for row in rows]


def get_top_trend_scores(limit: int = 20) -> list[dict]:
    """取出熱度分數最高的前 N 筆，作為「熱門排行榜」的資料來源。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT source, source_id, score, basis FROM trend_scores ORDER BY score DESC LIMIT %s",
            (limit,),
        ).fetchall()
        return [dict(row) for row in rows]


def upsert_narrations(rows: list[dict]) -> None:
    """寫入 LLM 產生的解說文字。每筆 row 需包含：source, source_id, narration, model, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO narrations (source, source_id, narration, model, created_at)
            VALUES (%(source)s, %(source_id)s, %(narration)s, %(model)s, %(created_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                narration = EXCLUDED.narration, model = EXCLUDED.model, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def get_narrations_map() -> dict:
    """回傳 (source, source_id) -> 解說文字 的對照表，供批次組裝清單（hydrate）時查表使用，
    避免對每個項目各自查一次資料庫。"""
    with get_connection() as conn:
        rows = conn.execute("SELECT source, source_id, narration FROM narrations").fetchall()
        return {(source, source_id): narration for source, source_id, narration in rows}
