"""Postgres 資料存取層：整個 pipeline（ingest / embed / classify / trend / recommend /
report / interact）共用同一份 Postgres 資料庫（Neon），這個模組集中管理 schema 定義與所有
讀寫函式，其他模組不直接寫 SQL，一律透過這裡提供的函式存取資料庫。
"""

import atexit
import os
from datetime import datetime, timezone
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row, tuple_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

# 本機開發時從專案根目錄的 .env 讀 DATABASE_URL（neon link 產生，已 gitignore）；
# 部署到 Render 時則由 Render Dashboard 設定同名環境變數，load_dotenv 不會覆蓋它。
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# 整個系統用到的資料表定義。用 CREATE TABLE IF NOT EXISTS 是為了讓 init_db()
# 可以每次啟動都安全地重複執行，不需要額外的 migration 機制。
# 時間欄位沿用 ISO 8601 字串（TEXT），跟 SQLite 時期的資料格式一致，字串排序即時間排序。
SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    source       TEXT NOT NULL,
    source_id    TEXT NOT NULL,
    title        TEXT NOT NULL,
    description  TEXT NOT NULL,
    url          TEXT NOT NULL,
    author       TEXT,
    category     TEXT,
    metric       BIGINT,
    published_at TEXT,
    fetched_at   TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS metric_snapshots (
    source      TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    metric      BIGINT NOT NULL,
    snapshot_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS embeddings (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    model      TEXT NOT NULL,
    vector     BYTEA NOT NULL,
    dim        INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS item_tags (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    tag        TEXT NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id, tag)
);

CREATE TABLE IF NOT EXISTS trend_scores (
    source      TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    score       DOUBLE PRECISION NOT NULL,
    basis       TEXT NOT NULL,
    computed_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE TABLE IF NOT EXISTS interactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    action     TEXT NOT NULL CHECK (action IN ('like', 'skip')),
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS narrations (
    source     TEXT NOT NULL,
    source_id  TEXT NOT NULL,
    narration  TEXT NOT NULL,
    model      TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (source, source_id)
);

CREATE INDEX IF NOT EXISTS metric_snapshots_source_idx ON metric_snapshots (source, snapshot_at);

-- 深讀清單：使用者丟進來的連結。抓取與翻譯由使用者電腦上的 reader_worker.py 處理
-- （Render 沒有 GPU、也連不到本機 Ollama），API 只負責收連結與提供閱讀。
CREATE TABLE IF NOT EXISTS reading_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url            TEXT NOT NULL UNIQUE,
    source         TEXT,
    source_id      TEXT,
    title          TEXT,
    title_zh       TEXT,
    authors        JSONB,
    published_at   TEXT,
    extraction     TEXT,
    warnings       JSONB,
    status         TEXT NOT NULL DEFAULT 'queued'
                   CHECK (status IN ('queued', 'fetching', 'translating', 'ready', 'failed')),
    error          TEXT,
    progress_done  INTEGER NOT NULL DEFAULT 0,
    progress_total INTEGER NOT NULL DEFAULT 0,
    read_progress  DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);

-- 原文區塊與譯文分開存：清單頁只讀 reading_items，不必搬動動輒幾百 KB 的全文。
CREATE TABLE IF NOT EXISTS reading_docs (
    item_id     BIGINT PRIMARY KEY REFERENCES reading_items (id) ON DELETE CASCADE,
    doc         JSONB NOT NULL,
    translation JSONB,
    updated_at  TEXT NOT NULL
);

-- 只有一列：本機翻譯 worker 最後一次回報的時間，閱讀頁用來顯示「翻譯站是否在線」。
CREATE TABLE IF NOT EXISTS reader_worker (
    id        INTEGER PRIMARY KEY CHECK (id = 1),
    model     TEXT,
    last_seen TEXT NOT NULL
);
"""


# 連線池：每次查詢都重新連線的話，光 TLS + 認證就要幾百毫秒，一頁要查幾十次（hydrate 對每個
# 項目各查一次），實測 /recommendations 從 SQLite 時期的瞬間變成 44 秒。所以改用連線池重用連線，
# 但 min_size=0 + max_idle=60：閒置 60 秒的連線會被關掉、一條都不留，Neon 才能在沒人用時休眠，
# 不會燒光免費方案每月的運算時數。
# DATABASE_URL 是 Neon 的 pooled endpoint（PgBouncer transaction mode），所以關掉 psycopg 的
# 自動 prepared statement（prepare_threshold=None），避免跨 PgBouncer 連線衝突。
_pool: ConnectionPool | None = None


def _reset(conn: psycopg.Connection) -> None:
    """連線歸還連線池時把 row_factory 還原成預設的 tuple：有些查詢會改成 dict_row，
    不還原的話下一個借到這條連線、用 tuple 拆解結果的函式會拿到 dict 而出錯。"""
    conn.row_factory = tuple_row


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        url = os.environ.get("DATABASE_URL")
        if not url:
            raise RuntimeError("DATABASE_URL 沒有設定：本機請在專案根目錄執行 neon link 產生 .env，部署環境請在 Render 設定環境變數。")
        _pool = ConnectionPool(
            url,
            min_size=0,
            max_size=4,
            max_idle=60,
            kwargs={"prepare_threshold": None, "connect_timeout": 15},
            reset=_reset,
            open=True,
        )
        atexit.register(_pool.close)
    return _pool


def get_connection():
    """從連線池借一條連線，搭配 with 使用：離開區塊時沒出錯就 commit、出錯就 rollback，再歸還連線池。"""
    return _get_pool().connection()


def init_db() -> None:
    """依 SCHEMA 建立所有資料表（已存在的表不會被動到），API 啟動、每支腳本執行前都會呼叫一次。"""
    with get_connection() as conn:
        for statement in SCHEMA.split(";"):
            if statement.strip():
                conn.execute(statement)


def upsert_items(items: list[dict]) -> int:
    """寫入項目，遇到已存在的（依 source+source_id 判斷）就略過，不覆蓋。

    回傳這次呼叫實際新增的筆數，讓呼叫端可以知道「這次抓到幾筆全新的項目」，
    而不是「這次總共處理了幾筆」。
    """
    with get_connection() as conn:
        cur = conn.cursor()
        cur.executemany(
            """
            INSERT INTO items
                (source, source_id, title, description, url, author, category, metric, published_at, fetched_at)
            VALUES
                (%(source)s, %(source_id)s, %(title)s, %(description)s, %(url)s, %(author)s, %(category)s,
                 %(metric)s, %(published_at)s, %(fetched_at)s)
            ON CONFLICT (source, source_id) DO NOTHING
            """,
            items,
        )
        return cur.rowcount


def record_snapshots(items: list[dict]) -> None:
    """不管項目本身是不是新的，每次抓取都幫每個項目多寫一筆指標快照（metric snapshot）。

    這是刻意設計成「每次都寫」而不是「只在項目是新的時候才寫」：
    之後計算「成長率」型的熱度分數（trend score）需要同一個項目在不同時間點的指標序列，
    只有持續累積快照才能還原出這條時間序列。
    """
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO metric_snapshots (source, source_id, metric, snapshot_at)
            VALUES (%(source)s, %(source_id)s, %(metric)s, %(fetched_at)s)
            """,
            items,
        )


def get_items_missing_embeddings() -> list[dict]:
    """找出 items 裡還沒有對應 embedding 紀錄的項目，供 embed.py 增量處理。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            """
            SELECT items.source, items.source_id, items.title, items.description
            FROM items
            LEFT JOIN embeddings
                ON items.source = embeddings.source AND items.source_id = embeddings.source_id
            WHERE embeddings.source_id IS NULL
            """
        ).fetchall()
        return [dict(row) for row in rows]


def upsert_embeddings(rows: list[dict]) -> None:
    """寫入 embedding 向量。每筆 row 需包含：source, source_id, model, vector（bytes）, dim, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO embeddings (source, source_id, model, vector, dim, created_at)
            VALUES (%(source)s, %(source_id)s, %(model)s, %(vector)s, %(dim)s, %(created_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                model = EXCLUDED.model, vector = EXCLUDED.vector, dim = EXCLUDED.dim, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def get_all_embeddings() -> list[dict]:
    """讀出所有項目的 embedding 向量，供 classify.py / api.py 的語意搜尋做線性掃描比對。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute("SELECT source, source_id, vector, dim FROM embeddings").fetchall()
        return [dict(row) for row in rows]


def upsert_tags(rows: list[dict]) -> None:
    """寫入標籤分類結果。每筆 row 需包含：source, source_id, tag, score, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO item_tags (source, source_id, tag, score, created_at)
            VALUES (%(source)s, %(source_id)s, %(tag)s, %(score)s, %(created_at)s)
            ON CONFLICT (source, source_id, tag) DO UPDATE SET
                score = EXCLUDED.score, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def upsert_trend_scores(rows: list[dict]) -> None:
    """寫入熱度分數。每筆 row 需包含：source, source_id, score, basis, computed_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO trend_scores (source, source_id, score, basis, computed_at)
            VALUES (%(source)s, %(source_id)s, %(score)s, %(basis)s, %(computed_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                score = EXCLUDED.score, basis = EXCLUDED.basis, computed_at = EXCLUDED.computed_at
            """,
            rows,
        )


def get_all_trend_scores() -> dict:
    """回傳 (source, source_id) -> 熱度分數 的對照表，方便其他模組整批查詢。"""
    with get_connection() as conn:
        rows = conn.execute("SELECT source, source_id, score FROM trend_scores").fetchall()
        return {(source, source_id): score for source, source_id, score in rows}


def record_interaction(source: str, source_id: str, action: str) -> None:
    """記錄一次使用者互動（按讚或略過），時間戳記統一用 UTC，避免跨時區比較時出錯。"""
    with get_connection() as conn:
        conn.execute(
            "INSERT INTO interactions (source, source_id, action, created_at) VALUES (%s, %s, %s, %s)",
            (source, source_id, action, datetime.now(timezone.utc).isoformat()),
        )


def get_latest_interactions() -> dict:
    """回傳 (source, source_id) -> 最新一次的動作（'like'/'skip'）。

    同一個項目可能被使用者按讚後又改成略過（或反過來），這裡只取每組
    (source, source_id) 裡 id 最大（也就是最新）的那一筆，讓「改變心意」可以覆蓋掉舊的判斷。
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT source, source_id, action FROM interactions
            WHERE id IN (SELECT MAX(id) FROM interactions GROUP BY source, source_id)
            """
        ).fetchall()
        return {(source, source_id): action for source, source_id, action in rows}


def get_item(source: str, source_id: str) -> dict | None:
    """依 (source, source_id) 查單一項目的完整欄位；查無資料回傳 None。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        row = conn.execute(
            "SELECT * FROM items WHERE source = %s AND source_id = %s", (source, source_id)
        ).fetchone()
        return dict(row) if row else None


def get_items_by_keys(keys: list[tuple[str, str]]) -> dict:
    """一次查回多個項目，回傳 (source, source_id) -> 項目欄位。

    給 API 批次組裝清單用：連線到 Neon 每次查詢都有網路往返成本，逐筆查 20 個項目
    （每筆再查一次標籤）實測要 20 秒，改成一次查完只要一次往返。
    """
    if not keys:
        return {}
    sources, ids = [k[0] for k in keys], [k[1] for k in keys]
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            """
            SELECT items.* FROM items
            JOIN unnest(%s::text[], %s::text[]) AS k(source, source_id) USING (source, source_id)
            """,
            (sources, ids),
        ).fetchall()
        return {(r["source"], r["source_id"]): dict(r) for r in rows}


def get_tags_for_keys(keys: list[tuple[str, str]]) -> dict:
    """一次查回多個項目的標籤，回傳 (source, source_id) -> [{tag, score}, ...]（分數高到低）。"""
    if not keys:
        return {}
    sources, ids = [k[0] for k in keys], [k[1] for k in keys]
    result: dict = {k: [] for k in keys}
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT item_tags.source, item_tags.source_id, tag, score FROM item_tags
            JOIN unnest(%s::text[], %s::text[]) AS k(source, source_id) USING (source, source_id)
            ORDER BY score DESC
            """,
            (sources, ids),
        ).fetchall()
    for source, source_id, tag, score in rows:
        result.setdefault((source, source_id), []).append({"tag": tag, "score": score})
    return result


def get_items(source: str | None = None, tag: str | None = None, limit: int = 50, offset: int = 0) -> list[dict]:
    """分頁列出項目，可選擇依來源（source）與標籤（tag）篩選。

    SQL 是用字串組合動態拼出來的：只有在有指定 tag 時才 JOIN item_tags 表、
    只有在有指定 source/tag 時才加對應的 WHERE 條件，避免不需要篩選時多做不必要的 JOIN。
    """
    query = "SELECT DISTINCT items.* FROM items"
    params: list = []
    where = []
    if tag:
        query += " JOIN item_tags ON items.source = item_tags.source AND items.source_id = item_tags.source_id"
        where.append("item_tags.tag = %s")
        params.append(tag)
    if source:
        where.append("items.source = %s")
        params.append(source)
    if where:
        query += " WHERE " + " AND ".join(where)
    query += " ORDER BY items.published_at DESC LIMIT %s OFFSET %s"
    params += [limit, offset]

    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(query, params).fetchall()
        return [dict(row) for row in rows]


def get_item_tags(source: str, source_id: str) -> list[dict]:
    """取得單一項目的所有標籤，依分數（score）由高到低排序。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT tag, score FROM item_tags WHERE source = %s AND source_id = %s ORDER BY score DESC",
            (source, source_id),
        ).fetchall()
        return [dict(row) for row in rows]


def get_tags_with_counts() -> list[dict]:
    """列出所有標籤與各自被使用的次數，依次數由多到少排序，供前端做標籤雲/篩選清單。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT tag, COUNT(*) as count FROM item_tags GROUP BY tag ORDER BY count DESC"
        ).fetchall()
        return [dict(row) for row in rows]


def get_top_trend_scores(limit: int = 20) -> list[dict]:
    """取出熱度分數最高的前 N 筆，作為「熱門排行榜」的資料來源。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        rows = conn.execute(
            "SELECT source, source_id, score, basis FROM trend_scores ORDER BY score DESC LIMIT %s",
            (limit,),
        ).fetchall()
        return [dict(row) for row in rows]


def upsert_narrations(rows: list[dict]) -> None:
    """寫入 LLM 產生的解說文字。每筆 row 需包含：source, source_id, narration, model, created_at。"""
    with get_connection() as conn:
        conn.cursor().executemany(
            """
            INSERT INTO narrations (source, source_id, narration, model, created_at)
            VALUES (%(source)s, %(source_id)s, %(narration)s, %(model)s, %(created_at)s)
            ON CONFLICT (source, source_id) DO UPDATE SET
                narration = EXCLUDED.narration, model = EXCLUDED.model, created_at = EXCLUDED.created_at
            """,
            rows,
        )


def get_narrations_map() -> dict:
    """回傳 (source, source_id) -> 解說文字 的對照表，供批次組裝清單（hydrate）時查表使用，
    避免對每個項目各自查一次資料庫。"""
    with get_connection() as conn:
        rows = conn.execute("SELECT source, source_id, narration FROM narrations").fetchall()
        return {(source, source_id): narration for source, source_id, narration in rows}


# ---------------------------------------------------------------- 深讀清單

READING_LIST_COLUMNS = (
    "id, url, source, source_id, title, title_zh, authors, published_at, extraction, warnings, "
    "status, error, progress_done, progress_total, read_progress, created_at, updated_at"
)
# update_reading_item() 只允許改這些欄位，避免呼叫端傳進任意欄位名稱拼進 SQL。
READING_UPDATABLE = {
    "source", "source_id", "title", "title_zh", "authors", "published_at", "extraction", "warnings",
    "status", "error", "progress_done", "progress_total", "read_progress",
}
READING_JSON_FIELDS = {"authors", "warnings"}


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def add_reading_item(url: str) -> dict:
    """加入深讀清單；同一個網址已經在清單裡就直接回傳原本那筆，不重複加。"""
    now = _utcnow()
    with get_connection() as conn:
        conn.row_factory = dict_row
        return conn.execute(
            f"""
            INSERT INTO reading_items (url, created_at, updated_at) VALUES (%s, %s, %s)
            ON CONFLICT (url) DO UPDATE SET url = EXCLUDED.url
            RETURNING {READING_LIST_COLUMNS}
            """,
            (url, now, now),
        ).fetchone()


def count_pending_reading_items() -> int:
    with get_connection() as conn:
        return conn.execute(
            "SELECT COUNT(*) FROM reading_items WHERE status IN ('queued', 'fetching', 'translating')"
        ).fetchone()[0]


def list_reading_items() -> list[dict]:
    """清單頁用：不帶全文，只多帶重點整理的那一句話（one_line），讓使用者不用點進去就知道在講什麼。"""
    cols = ", ".join(f"reading_items.{c.strip()}" for c in READING_LIST_COLUMNS.split(","))
    with get_connection() as conn:
        conn.row_factory = dict_row
        return conn.execute(
            f"""
            SELECT {cols}, reading_docs.translation -> 'summary' ->> 'one_line' AS one_line
            FROM reading_items LEFT JOIN reading_docs ON reading_docs.item_id = reading_items.id
            ORDER BY reading_items.created_at DESC
            """
        ).fetchall()


def get_reading_item(item_id: int, with_content: bool = False) -> dict | None:
    """with_content=True 時一併帶回原文區塊（doc）與譯文（translation），給閱讀頁用。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        if with_content:
            cols = ", ".join(f"reading_items.{c.strip()}" for c in READING_LIST_COLUMNS.split(","))
            return conn.execute(
                f"""
                SELECT {cols}, reading_docs.doc, reading_docs.translation
                FROM reading_items LEFT JOIN reading_docs ON reading_docs.item_id = reading_items.id
                WHERE reading_items.id = %s
                """,
                (item_id,),
            ).fetchone()
        return conn.execute(f"SELECT {READING_LIST_COLUMNS} FROM reading_items WHERE id = %s", (item_id,)).fetchone()


def update_reading_item(item_id: int, **fields) -> None:
    unknown = set(fields) - READING_UPDATABLE
    if unknown:
        raise ValueError(f"不能更新的欄位：{unknown}")
    if not fields:
        return
    values = [Jsonb(v) if k in READING_JSON_FIELDS and v is not None else v for k, v in fields.items()]
    sets = ", ".join(f"{k} = %s" for k in fields)
    with get_connection() as conn:
        conn.execute(
            f"UPDATE reading_items SET {sets}, updated_at = %s WHERE id = %s",
            (*values, _utcnow(), item_id),
        )


def delete_reading_item(item_id: int) -> bool:
    with get_connection() as conn:
        return conn.execute("DELETE FROM reading_items WHERE id = %s", (item_id,)).rowcount > 0


def save_reading_doc(item_id: int, doc: dict) -> None:
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO reading_docs (item_id, doc, updated_at) VALUES (%s, %s, %s)
            ON CONFLICT (item_id) DO UPDATE SET doc = EXCLUDED.doc, updated_at = EXCLUDED.updated_at
            """,
            (item_id, Jsonb(doc), _utcnow()),
        )


def save_reading_translation(item_id: int, translation: dict) -> None:
    with get_connection() as conn:
        conn.execute(
            "UPDATE reading_docs SET translation = %s, updated_at = %s WHERE item_id = %s",
            (Jsonb(translation), _utcnow(), item_id),
        )


def get_reading_doc(item_id: int) -> tuple[dict | None, dict | None]:
    with get_connection() as conn:
        row = conn.execute("SELECT doc, translation FROM reading_docs WHERE item_id = %s", (item_id,)).fetchone()
        return (row[0], row[1]) if row else (None, None)


def claim_next_reading_item() -> dict | None:
    """worker 取下一筆排隊中的項目並標成 fetching。只有一個 worker，SKIP LOCKED 是保險。"""
    with get_connection() as conn:
        conn.row_factory = dict_row
        return conn.execute(
            f"""
            UPDATE reading_items SET status = 'fetching', error = NULL, updated_at = %s
            WHERE id = (
                SELECT id FROM reading_items WHERE status = 'queued'
                ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED
            )
            RETURNING {READING_LIST_COLUMNS}
            """,
            (_utcnow(),),
        ).fetchone()


def requeue_interrupted_reading_items() -> int:
    """worker 啟動時呼叫：上次執行到一半被中斷（電腦關機）的項目放回佇列，譯文已存的部分會沿用。"""
    with get_connection() as conn:
        return conn.execute(
            "UPDATE reading_items SET status = 'queued', updated_at = %s WHERE status IN ('fetching', 'translating')",
            (_utcnow(),),
        ).rowcount


def worker_heartbeat(model: str) -> None:
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO reader_worker (id, model, last_seen) VALUES (1, %s, %s)
            ON CONFLICT (id) DO UPDATE SET model = EXCLUDED.model, last_seen = EXCLUDED.last_seen
            """,
            (model, _utcnow()),
        )


def get_worker_status() -> dict | None:
    with get_connection() as conn:
        conn.row_factory = dict_row
        return conn.execute("SELECT model, last_seen FROM reader_worker WHERE id = 1").fetchone()


def reading_ids_missing_summary() -> list[int]:
    """已經翻好、但譯文裡還沒有重點整理的項目（重點整理功能加入前翻好的文章要補）。"""
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT reading_docs.item_id FROM reading_docs
            JOIN reading_items ON reading_items.id = reading_docs.item_id
            WHERE reading_items.status = 'ready' AND reading_docs.translation IS NOT NULL
              AND jsonb_typeof(reading_docs.translation -> 'summary') IS DISTINCT FROM 'object'
            """
        ).fetchall()
    return [r[0] for r in rows]
